# Generated by Django 4.1.7 on 2023-04-09 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='data',
            field=models.DateField(default=datetime.date(2023, 4, 9)),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
