# Generated by Django 4.1.7 on 2023-04-13 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0003_alter_warehouse_data_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
