# Generated by Django 4.1.7 on 2023-04-13 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example_app', '0004_alter_deal_data_alter_warehouse_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='price_by_one',
            field=models.IntegerField(verbose_name='Цена за ед.'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app.product', verbose_name='Продукт'),
        ),
    ]
